### ISSUE TITLE
stop_app is not defined in server.py

### ISSUE THREAD

**Issue by rmuslimov** [abingham/traad#79]
I've tried to start with wrong port number, and I've got

`Traceback (most recent call last):
  File "/Users/rmuslimov/.virtualenvs/cessna/bin/traad", line 9, in <module>
    load_entry_point('traad==0.12', 'console_scripts', 'traad')()
  File "/Users/rmuslimov/.virtualenvs/cessna/lib/python2.7/site-packages/traad/server.py", line 60, in main
    run_server(app, args.port)
  File "/Users/rmuslimov/.virtualenvs/cessna/lib/python2.7/site-packages/traad/server.py", line 24, in run_server
    stop_app(app)
NameError: global name 'stop_app' is not defined
`
It's minot issue, but let's fix it

**Comment by abingham** [comment]
Good catch. Have a look at [this PR](https://github.com/abingham/traad/pull/80) and let me know if it looks OK to you. If so, I'll merge it in. Thanks!

**Comment by rmuslimov** [comment]
Yep, thanks for quick reply. It will work, let's merge it. thanks!

**Comment by abingham** [comment]
Fixed in 66e790cbf4a2a8726393536048b8e83b45d5d6e6
